### ISSUE TITLE
H36M data link

### ISSUE THREAD

**Issue by strawberryfg** [CHUNYUWANG/pacom#3]
I'm sorry but it appears that the download link for H36M is not working. It shows "this item might not exist or is no longer available"?

**Comment by CHUNYUWANG** [comment]
It can be downloaded here.

https://pan.baidu.com/s/1V65vwuAtTUd5Wy5IDlGiaw

**Comment by zhanghczzz** [comment]
> It can be downloaded here.
> 
> https://pan.baidu.com/s/1V65vwuAtTUd5Wy5IDlGiaw

Hi, I use the pkl file to evaluate the cross-view, but it doesn't have the 'joints_3d_camera' key.  Can you share the cross-view pkl file? Thank you!
